name: split_bill
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8

  equatable: ^2.0.7
  flutter:
    sdk: flutter
  concentric_transition: ^1.0.3
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.4.4
  sqflite: ^2.4.1
  path: ^1.9.0

  gap: ^3.0.1
  go_router: ^14.6.1
  mobile_scanner: ^6.0.2
  fl_chart: ^0.69.2
  retrofit: ^4.4.1
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  qr_flutter: ^4.1.0
  freezed: ^2.5.7
  dartz: ^0.10.1
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.2
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_annotation: ^4.9.0

  json_serializable: ^6.9.0
  pretty_logger: ^1.0.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/images/1page.png
    - assets/images/2page.png
    - assets/images/3page.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
