name: split_bill
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8

  equatable: ^2.0.7
  flutter:
    sdk: flutter
  concentric_transition: ^1.0.3
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.4.4
  sqflite: ^2.4.1
  path: ^1.9.0

  gap: ^3.0.1
  go_router: ^14.6.1
  mobile_scanner: ^6.0.2
  fl_chart: ^0.69.2
  retrofit: ^4.4.1
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  qr_flutter: ^4.1.0
  freezed: ^2.5.7
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_annotation: ^4.9.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  json_serializable: ^6.9.0
  pretty_logger: ^1.0.0
  retrofit_generator: ^9.1.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/images/1page.png
    - assets/images/2page.png
    - assets/images/3page.png
    - assets/png/person-0.png
    - assets/png/person-1.png
    - assets/png/person-2.png
    - assets/png/person-3.png
    - assets/png/person-4.png
    - assets/png/person-5.png
    - assets/png/person-6.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
